name:  Dartrix
description:  Matrix rain with Dart. Inspired by https://github.com/hendo13/HTML5-Matrix-Code-Rain/
dependencies:
  browser: any
dev_dependencies:
  runtime:
    path: ../../../web_runtime
